<a href="https://colab.research.google.com/github/elghallali/deep-learning/blob/master/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf

# Define the training data for logic gates
# For each gate, we'll have two input values and one output.
# You can add more data points if needed.
logic_gates = {
    "AND": {
        "input": tf.constant([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=tf.float32),
        "output": tf.constant([[0], [0], [0], [1]], dtype=tf.float32),
    },
    "OR": {
        "input": tf.constant([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=tf.float32),
        "output": tf.constant([[0], [1], [1], [1]], dtype=tf.float32),
    },
    "XOR": {
        "input": tf.constant([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=tf.float32),
        "output": tf.constant([[0], [1], [1], [0]], dtype=tf.float32),
    },
}

# Define a simple neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(2,)),  # Input layer with 2 neurons
    tf.keras.layers.Dense(2, activation='sigmoid'),  # Hidden layer with 2 neurons and sigmoid activation
    tf.keras.layers.Dense(1, activation='sigmoid'),  # Output layer with 1 neuron and sigmoid activation
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model for each logic gate
for gate, data in logic_gates.items():
    print(f"Training {gate} gate...")
    model.fit(data["input"], data["output"], epochs=1000, verbose=0)

    # Evaluate the model
    loss = model.evaluate(data["input"], data["output"])
    print(f"Loss for {gate} gate: {loss:.4f}")

# Test the model
input_data = tf.constant([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=tf.float32)
output = model.predict(input_data)
print("Model predictions:")
print(output)


Training AND gate...
1/1 [==============================] - 0s 93ms/step - loss: 0.1363
Loss for AND gate: 0.1363
Training OR gate...
1/1 [==============================] - 0s 22ms/step - loss: 0.1054
Loss for OR gate: 0.1054
Training XOR gate...
1/1 [==============================] - 0s 34ms/step - loss: 0.2053
Loss for XOR gate: 0.2053
1/1 [==============================] - 0s 98ms/step
Model predictions:
[[0.24030194]
 [0.6580527 ]
 [0.61181694]
 [0.70422155]]


In [11]:
import numpy as np

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define the training data for logic gates
# For each gate, we'll have two input values and one output.
# You can add more data points if needed.
logic_gates = {
    "AND": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [0], [0], [1]]),
    },
    "OR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [1]]),
    },
    "XOR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [0]]),
    },
}

# Define the neural network architecture
input_size = 2
hidden_size = 4
output_size = 1

# Initialize the weights and biases for the neural network
np.random.seed(0)
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
bias_hidden = np.zeros((1, hidden_size))
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))
bias_output = np.zeros((1, output_size))

# Define the learning rate and the number of epochs
learning_rate = 0.1
epochs = 10000

# Train the neural network for each logic gate
for gate, data in logic_gates.items():
    print(f"Training {gate} gate...")
    for epoch in range(epochs):
        # Forward propagation
        input_layer = data["input"]
        hidden_layer_input = np.dot(input_layer, weights_input_hidden) + bias_hidden
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
        output_layer_output = sigmoid(output_layer_input)

        # Backpropagation
        error = data["output"] - output_layer_output
        d_output = error * sigmoid_derivative(output_layer_output)
        error_hidden = d_output.dot(weights_hidden_output.T)
        d_hidden = error_hidden * sigmoid_derivative(hidden_layer_output)

        # Update weights and biases
        weights_hidden_output += hidden_layer_output.T.dot(d_output) * learning_rate
        bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate
        weights_input_hidden += input_layer.T.dot(d_hidden) * learning_rate
        bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    print(f"Training completed for {gate} gate.")

    # Test the model
    predicted_output = output_layer_output
    print(f"Model predictions for {gate} gate:")
    print(predicted_output)



Training AND gate...
Training completed for AND gate.
Model predictions for AND gate:
[[0.00266931]
 [0.03241783]
 [0.03213896]
 [0.96235904]]
Training OR gate...
Training completed for OR gate.
Model predictions for OR gate:
[[0.02036567]
 [0.99069491]
 [0.99059323]
 [0.99987206]]
Training XOR gate...
Training completed for XOR gate.
Model predictions for XOR gate:
[[0.01538757]
 [0.98993839]
 [0.98978802]
 [0.99978929]]


In [13]:
import numpy as np

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define the training data for logic gates
# For each gate, we'll have two input values and one output.
# You can add more data points if needed.
logic_gates = {
    "AND": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [0], [0], [1]]),
    },
    "OR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [1]]),
    },
    "XOR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [0]]),
    },
}

# Define the neural network architecture
input_size = 2
hidden_size = 1
output_size = 1

# Initialize the weights and biases for the neural network
np.random.seed(0)
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
bias_hidden = np.zeros((1, hidden_size))
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))
bias_output = np.zeros((1, output_size))

# Define the learning rate and the number of epochs
learning_rate = 0.1
epochs = 10000

# Train the neural network for each logic gate
for gate, data in logic_gates.items():
    print(f"Training {gate} gate...")
    for epoch in range(epochs):
        # Forward propagation
        input_layer = data["input"]
        hidden_layer_input = np.dot(input_layer, weights_input_hidden) + bias_hidden
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
        output_layer_output = sigmoid(output_layer_input)

        # Backpropagation
        error = data["output"] - output_layer_output
        d_output = error * sigmoid_derivative(output_layer_output)
        error_hidden = d_output.dot(weights_hidden_output.T)
        d_hidden = error_hidden * sigmoid_derivative(hidden_layer_output)

        # Update weights and biases
        weights_hidden_output += hidden_layer_output.T.dot(d_output) * learning_rate
        bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate
        weights_input_hidden += input_layer.T.dot(d_hidden) * learning_rate
        bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    print(f"Training completed for {gate} gate.")

    # Test the model
    predicted_output = output_layer_output
    print(f"Model predictions for {gate} gate:")
    print(predicted_output)


Training AND gate...
Training completed for AND gate.
Model predictions for AND gate:
[[0.01107031]
 [0.03425   ]
 [0.03424999]
 [0.95676796]]
Training OR gate...
Training completed for OR gate.
Model predictions for OR gate:
[[0.02714498]
 [0.98689839]
 [0.98689839]
 [0.99620898]]
Training XOR gate...
Training completed for XOR gate.
Model predictions for XOR gate:
[[0.0294738 ]
 [0.66564259]
 [0.66564259]
 [0.66763096]]


In [15]:
import numpy as np

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define the training data for logic gates
# For each gate, we'll have two input values and one output.
# You can add more data points if needed.
logic_gates = {
    "AND": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [0], [0], [1]]),
    },
    "OR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [1]]),
    },
    "XOR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [0]]),
    },
}

# Define the neural network architecture
input_size = 2
hidden_size = 2
output_size = 1

# Initialize the weights and biases for the neural network
np.random.seed(0)
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
bias_hidden = np.zeros((1, hidden_size))
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))
bias_output = np.zeros((1, output_size))

# Define the learning rate and the number of epochs
learning_rate = 0.1
epochs = 10000

# Train the neural network for each logic gate
for gate, data in logic_gates.items():
    print(f"Training {gate} gate...")
    for epoch in range(epochs):
        # Forward propagation
        input_layer = data["input"]
        hidden_layer_input = np.dot(input_layer, weights_input_hidden) + bias_hidden
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
        output_layer_output = sigmoid(output_layer_input)

        # Backpropagation
        error = data["output"] - output_layer_output
        d_output = error * sigmoid_derivative(output_layer_output)
        error_hidden = d_output.dot(weights_hidden_output.T)
        d_hidden = error_hidden * sigmoid_derivative(hidden_layer_output)

        # Update weights and biases
        weights_hidden_output += hidden_layer_output.T.dot(d_output) * learning_rate
        bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate
        weights_input_hidden += input_layer.T.dot(d_hidden) * learning_rate
        bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    print(f"Training completed for {gate} gate.")

    # Test the model
    predicted_output = output_layer_output
    print(f"Model predictions for {gate} gate:")
    print(predicted_output)


Training AND gate...
Training completed for AND gate.
Model predictions for AND gate:
[[0.00490918]
 [0.03255827]
 [0.0324735 ]
 [0.96139735]]
Training OR gate...
Training completed for OR gate.
Model predictions for OR gate:
[[0.02258463]
 [0.98971866]
 [0.98967013]
 [0.9993729 ]]
Training XOR gate...
Training completed for XOR gate.
Model predictions for XOR gate:
[[0.04522839]
 [0.66383746]
 [0.66383514]
 [0.6719748 ]]


In [16]:
import numpy as np

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define the training data for logic gates
# For each gate, we'll have two input values and one output.
# You can add more data points if needed.
logic_gates = {
    "AND": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [0], [0], [1]]),
    },
    "OR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [1]]),
    },
    "XOR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [0]]),
    },
}

# Define the neural network architecture
input_size = 2
hidden_size = 3
output_size = 1

# Initialize the weights and biases for the neural network
np.random.seed(0)
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
bias_hidden = np.zeros((1, hidden_size))
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))
bias_output = np.zeros((1, output_size))

# Define the learning rate and the number of epochs
learning_rate = 0.1
epochs = 10000

# Train the neural network for each logic gate
for gate, data in logic_gates.items():
    print(f"Training {gate} gate...")
    for epoch in range(epochs):
        # Forward propagation
        input_layer = data["input"]
        hidden_layer_input = np.dot(input_layer, weights_input_hidden) + bias_hidden
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
        output_layer_output = sigmoid(output_layer_input)

        # Backpropagation
        error = data["output"] - output_layer_output
        d_output = error * sigmoid_derivative(output_layer_output)
        error_hidden = d_output.dot(weights_hidden_output.T)
        d_hidden = error_hidden * sigmoid_derivative(hidden_layer_output)

        # Update weights and biases
        weights_hidden_output += hidden_layer_output.T.dot(d_output) * learning_rate
        bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate
        weights_input_hidden += input_layer.T.dot(d_hidden) * learning_rate
        bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    print(f"Training completed for {gate} gate.")

    # Test the model
    predicted_output = output_layer_output
    print(f"Model predictions for {gate} gate:")
    print(predicted_output)


Training AND gate...
Training completed for AND gate.
Model predictions for AND gate:
[[0.00419594]
 [0.03182481]
 [0.03185736]
 [0.96216861]]
Training OR gate...
Training completed for OR gate.
Model predictions for OR gate:
[[0.02222418]
 [0.98991799]
 [0.98993358]
 [0.99959742]]
Training XOR gate...
Training completed for XOR gate.
Model predictions for XOR gate:
[[0.01593815]
 [0.67336349]
 [0.67492658]
 [0.55286593]]


In [17]:
import numpy as np

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define the training data for logic gates
# For each gate, we'll have two input values and one output.
# You can add more data points if needed.
logic_gates = {
    "AND": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [0], [0], [1]]),
    },
    "OR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [1]]),
    },
    "XOR": {
        "input": np.array([[0, 0], [0, 1], [1, 0], [1, 1]]),
        "output": np.array([[0], [1], [1], [0]]),
    },
}

# Define the neural network architecture
input_size = 2
hidden_size = 5
output_size = 1

# Initialize the weights and biases for the neural network
np.random.seed(0)
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
bias_hidden = np.zeros((1, hidden_size))
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))
bias_output = np.zeros((1, output_size))

# Define the learning rate and the number of epochs
learning_rate = 0.1
epochs = 10000

# Train the neural network for each logic gate
for gate, data in logic_gates.items():
    print(f"Training {gate} gate...")
    for epoch in range(epochs):
        # Forward propagation
        input_layer = data["input"]
        hidden_layer_input = np.dot(input_layer, weights_input_hidden) + bias_hidden
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
        output_layer_output = sigmoid(output_layer_input)

        # Backpropagation
        error = data["output"] - output_layer_output
        d_output = error * sigmoid_derivative(output_layer_output)
        error_hidden = d_output.dot(weights_hidden_output.T)
        d_hidden = error_hidden * sigmoid_derivative(hidden_layer_output)

        # Update weights and biases
        weights_hidden_output += hidden_layer_output.T.dot(d_output) * learning_rate
        bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate
        weights_input_hidden += input_layer.T.dot(d_hidden) * learning_rate
        bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    print(f"Training completed for {gate} gate.")

    # Test the model
    predicted_output = output_layer_output
    print(f"Model predictions for {gate} gate:")
    print(predicted_output)


Training AND gate...
Training completed for AND gate.
Model predictions for AND gate:
[[5.22861976e-04]
 [2.60077706e-02]
 [2.62308200e-02]
 [9.66920103e-01]]
Training OR gate...
Training completed for OR gate.
Model predictions for OR gate:
[[0.01346006]
 [0.99227471]
 [0.99233115]
 [0.99994229]]
Training XOR gate...
Training completed for XOR gate.
Model predictions for XOR gate:
[[0.01137373]
 [0.99258921]
 [0.99266716]
 [0.99993722]]
